// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/coderlewin/ucenter/internal/infrastructure/persistence/mysql"
	"github.com/coderlewin/ucenter/internal/repository"
	"github.com/coderlewin/ucenter/internal/service"
	"github.com/coderlewin/ucenter/internal/web"
	"github.com/coderlewin/ucenter/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	v := ioc.CommonMiddlewares()
	db := ioc.InitDB()
	userDAO := mysql.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	hertz := ioc.InitWebServer(v, userHandler)
	app := &App{
		web: hertz,
	}
	return app
}
